class StringConst {
  static const String welcomeLabel = "Welcome!";
  static const String gitTransferLabel = "GIT Transfer!";
  static const String invalidCredentialsError = "Invalid Credentials";
  static const String loginLabel = "Login";
  static const String registrationLabel = "Registration";
  static const String createTransactionLabel = "Create Transaction";
  static const String usernameLabel = "Username";
  static const String passwordLabel = "Password";
  static const String userRegistrationLabel = "User Registration";
  static const String saveLabel = "Save";
  static const String cancelLabel = "Cancel";
  static const String dataNotFoundLabel = "Data Not Found";
  static const String noOfTransactionsLabel = "No of Transactions";
  static const String transactionsLabel = "Transactions";
  static const String statisticsLabel = "Statistics";
  static const String transactionSummaryLabel = "Transaction Summary";
  static const String transactionDateLabel = "Transaction date";
  static const String amountLabel = "Amount";
  static const String commissionLabel = "Commission";
  static const String totalLabel = "Total";
  static const String transactionNumberLabel = "Transaction number";
  static const String typeOfOperationLabel = "Type of operation";
  static const String typeOfTransactionLabel = "Type of Transaction";
  static const String yesLabel = "Yes";
  static const String noThanksLabel = "No, Thanks";
  static const String logoutMsgLabel = "Are you sure you want to log out?";
  static const String transactionAddedSuccessfullyMsgLabel = "Transaction added successfully";
  static const String cancelTransactionLabel =
      "Are you sure you want to cancel this transaction?";
  static const String cancelTransactionLabel2 ="transaction has been canceled.";
  static const String userRegisteredSuccessfullyLabel ="User registered successfully.";
  static const String yearlyReplenishmentAnalysisLabel ="Yearly Replenishment Analysis";
  static const String replenishmentLabel ="Replenishment";
  static const String yearlyTransferAnalysisLabel ="Yearly Transfer Analysis";
  static const String transferLabel ="Transfer";
  static const String yearlyWithdrawalAnalysisLabel ="Yearly Withdrawal Analysis";
  static const String withdrawalLabel ="Withdrawal";
}
